CREATE OR REPLACE PROCEDURE LIMPAR_MODELO_ESTRELA IS
BEGIN
    -- Limpeza da tabela CP4_FATO (precisa acontecer primeiro devido às chaves estrangeiras)
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CP4_FATO_VENDAS';
    
    -- Limpeza das CP4_DIMensões
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CP4_DIM_CLIENTE';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CP4_DIM_PRODUTO';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CP4_DIM_VENDEDOR';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CP4_DIM_TEMPO';
    EXECUTE IMMEDIATE 'TRUNCATE TABLE CP4_DIM_LOCALIZACAO';
    
    -- Reseta as sequências
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_SK_CLIENTE RESTART START WITH 1';
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_SK_PRODUTO RESTART START WITH 1';
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_SK_VENDEDOR RESTART START WITH 1';
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_SK_TEMPO RESTART START WITH 1';
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_SK_LOCALIZACAO RESTART START WITH 1';
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_SK_VENDA RESTART START WITH 1';
    
    DBMS_OUTPUT.PUT_LINE('Modelo estrela limpo com sucesso.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro ao limpar modelo estrela: ' || SQLERRM);
        ROLLBACK;
END LIMPAR_MODELO_ESTRELA;
/